### ISSUE TITLE
Questions for J

### ISSUE THREAD

**Issue by richardtemple** [richardtemple/retirement_calculator#6]
Why calculators#new for root rather than calculators/new in Routes.rb?

**Comment by gwhilts** [comment]
I'm a little confused.  'calculators/new' isn't a thing. Or rather it's route, but not one that exists in our app. 

Are you asking why we did this:

    root 'calculators#new'

instead of:

    get 'financial_calculator/new', to: 'calculators#new'

Both are fine, but the latter option is good (and very RESTful), but wouldn't have left users going to the root of the site without any response. We could fix that by then adding a redirect for root:

    get   '/financial_calculator/new', to: 'calculators#new'
    root  to: redirect('financial_calculator/new')

**Comment by richardtemple** [comment]
Yes, old question...  In the Agile book, the routes had these:
  get "session/create"
and I was wondering why the pound sign on the 'root' setting, but a slash on the 'get' setting.

**Comment by gwhilts** [comment]
Slashes are only used when describing part of a URL: `http://myapp.com/path/path`

The pound sign is used when describing an instance method: `mycontroller#mymethod`

Thus the standard root map rule has both:

    get 'path/path', to: 'controller#method'

the root map doesn't need the URL path part of the rule because it's always just '/' so it's just

    root 'controller#method'

**Comment by richardtemple** [comment]
but if there is no ", to 'controller#method'", like 
get "session/create"
It must magically figure out that I want the sessions controller and call the create method?

**Comment by gwhilts** [comment]
Yes, if you omit the action portion of the rule, it will look for a controller and method that match the path values.

Remember, if you ever have a question about your route map, you can add a rule to your config/routes.rb file, then type

    rake routes

at the command line.

You'll get nice table, showing all the available routes like so:

````
              Prefix Verb  URI Pattern                     Controller#Action
     edit_calculator GET   /financial_calculator(.:format) calculators#edit
          calculator PUT   /financial_calculator(.:format) calculators#update
financial_calculator PATCH /financial_calculator(.:format) calculators#update
                     POST  /financial_calculator(.:format) calculators#update
                root GET   /                               calculators#new
````
